# Generated by Django 5.2.2 on 2025-06-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='theater_id',
        ),
        migrations.AddField(
            model_name='theater',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='theater',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
