# Generated by Django 5.2.2 on 2025-06-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0004_showtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='Showtime',
            new_name='showtime',
        ),
    ]
