# Generated by Django 5.2.2 on 2025-07-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0005_rename_showtime_showtime_showtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='recliner_price',
            new_name='platinum_price',
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=50),
        ),
        migrations.AlterField(
            model_name='theater',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='theater',
            name='city',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(max_length=2500),
        ),
    ]
