# Generated by Django 5.2.2 on 2025-07-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0006_rename_recliner_price_showtime_platinum_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='platinum_price',
            new_name='recliner_price',
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('silver', 'silver'), ('gold', 'gold'), ('recliner', 'recliner')], max_length=100),
        ),
        migrations.AlterField(
            model_name='theater',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
