# Generated by Django 5.2.2 on 2025-07-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_showtime_movie_remove_showtime_theater_and_more'),
        ('theaters', '0006_rename_recliner_price_showtime_platinum_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='booking_seat',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Showtime',
            new_name='showtimes',
        ),
        migrations.RenameField(
            model_name='bookingseat',
            old_name='seat',
            new_name='Seats',
        ),
        migrations.RenameField(
            model_name='bookingseat',
            old_name='Booking',
            new_name='booking',
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theaters.showtime'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('booked', 'booked')], default='pending', max_length=50),
        ),
    ]
