# Generated by Django 5.2.2 on 2025-07-03 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_booking_time_booking_booking_seat_and_more'),
        ('theaters', '0007_rename_platinum_price_showtime_recliner_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_seat',
            new_name='booking_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='showtimes',
            new_name='showtime',
        ),
        migrations.RenameField(
            model_name='bookingseat',
            old_name='Seats',
            new_name='seat',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('booked', 'booked')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingseat',
            name='showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theaters.showtime'),
        ),
    ]
