# Generated by Django 5.2.2 on 2025-06-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Fiction', 'Fiction'), ('Adventure', 'Adventure')], max_length=255),
        ),
    ]
