# Generated by Django 5.2.2 on 2025-06-20 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Fantasy', 'Fantasy'), ('Thriller', 'Thriller'), ('Animation', 'Animation'), ('Documentary', 'Documentary')], max_length=250)),
                ('language', models.CharField(choices=[('kannada', 'kannada'), ('english', 'english'), ('hindi', 'hindi'), ('tamil', 'tamil'), ('telugu', 'telugu'), ('malayalam', 'malayalam')], max_length=250)),
                ('synopsis', models.TextField()),
                ('cast', models.TextField(default=None)),
                ('duration_minutes', models.IntegerField()),
                ('releases_date', models.DateField()),
                ('triler_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='movies.movies'),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
