# Generated by Django 5.2.2 on 2025-06-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movies_alter_cast_movie_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='releases_date',
            new_name='release_date',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='cast',
        ),
    ]
