# Generated by Django 5.2.2 on 2025-06-21 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_releases_date_movies_release_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], max_length=200, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('Kannada', 'Kannada'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Malayalam', 'Malayalam')], max_length=200, null=True)),
                ('synopsis', models.TextField(blank=True, max_length=255, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Released', 'Released'), ('Upcoming', 'Upcoming')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('slug', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cast',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cast',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='movies.movie'),
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
