# Generated by Django 5.2.2 on 2025-06-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_alter_cast_name_alter_cast_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=2000, unique=True),
            preserve_default=False,
        ),
    ]
