# Generated by Django 5.2.2 on 2025-06-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Marathi', 'Marathi'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('Kannada', 'Kannada'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Malayalam', 'Malayalam')], max_length=200, null=True),
        ),
    ]
