# Generated by Django 5.2.2 on 2025-07-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_image',
        ),
        migrations.AddField(
            model_name='movie',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
